### ISSUE TITLE
DAT compile error

### ISSUE THREAD

**Issue by matewfeel** [exsstas/StyleTransfer-in-TD#1]
Hey There i'm getting this error when after pressing ' run style transfer'; i think it's related to different version of Numpy/Scipy, but as i'm well unexperienced in coding my hands are tight ;
I followed all your steps, i can get to test tensorflow with 'import tensorflow as tf''... and so on... then in CMD i run ''activate tensorflow'' then, "conda install Numpy & Scipy; then back in TD i run in textport "import numpy
numpy"; 
and i can see the directory of Numpy; ( i also tried importing scipy );
i then placed VGG 19 in project dir;

I'm running TD 099, this is the error: 

:

python >>> 
DAT compile error: /StyleTransfer/local/modules/main
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "/StyleTransfer/local/modules/main", line 10, in <module>
  File "E:/Program Files/Derivative/TouchDesigner 099/bin/TouchInit.py", line 175, in tdcustomimport
    r = previousimport(*args, **kw)
  File "C:/Users/matteo/Anaconda3/envs/tensorflow/Lib/site-packages\scipy\io\__init__.py", line 97, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
  File "E:/Program Files/Derivative/TouchDesigner 099/bin/TouchInit.py", line 175, in tdcustomimport
    r = previousimport(*args, **kw)
  File "C:/Users/matteo/Anaconda3/envs/tensorflow/Lib/site-packages\scipy\io\matlab\__init__.py", line 13, in <module>
    from .mio import loadmat, savemat, whosmat
  File "E:/Program Files/Derivative/TouchDesigner 099/bin/TouchInit.py", line 175, in tdcustomimport
    r = previousimport(*args, **kw)
  File "C:/Users/matteo/Anaconda3/envs/tensorflow/Lib/site-packages\scipy\io\matlab\mio.py", line 12, in <module>
    from .miobase import get_matfile_version, docfiller
  File "E:/Program Files/Derivative/TouchDesigner 099/bin/TouchInit.py", line 175, in tdcustomimport
    r = previousimport(*args, **kw)
  File "C:/Users/matteo/Anaconda3/envs/tensorflow/Lib/site-packages\scipy\io\matlab\miobase.py", line 22, in <module>
    from scipy.misc import doccer
  File "E:/Program Files/Derivative/TouchDesigner 099/bin/TouchInit.py", line 175, in tdcustomimport
    r = previousimport(*args, **kw)
  File "C:/Users/matteo/Anaconda3/envs/tensorflow/Lib/site-packages\scipy\misc\__init__.py", line 53, in <module>
    from scipy.interpolate._pade import pade
  File "E:/Program Files/Derivative/TouchDesigner 099/bin/TouchInit.py", line 175, in tdcustomimport
    r = previousimport(*args, **kw)
  File "E:/Program Files/Derivative/TouchDesigner 099/bin/TouchInit.py", line 175, in tdcustomimport
    r = previousimport(*args, **kw)
  File "C:/Users/matteo/Anaconda3/envs/tensorflow/Lib/site-packages\scipy\interpolate\__init__.py", line 176, in <module>
    from .interpolate import *
  File "E:/Program Files/Derivative/TouchDesigner 099/bin/TouchInit.py", line 175, in tdcustomimport
    r = previousimport(*args, **kw)
  File "C:/Users/matteo/Anaconda3/envs/tensorflow/Lib/site-packages\scipy\interpolate\interpolate.py", line 20, in <module>
    import scipy.linalg
  File "E:/Program Files/Derivative/TouchDesigner 099/bin/TouchInit.py", line 175, in tdcustomimport
    r = previousimport(*args, **kw)
  File "C:/Users/matteo/Anaconda3/envs/tensorflow/Lib/site-packages\scipy\linalg\__init__.py", line 175, in <module>
    from .misc import *
  File "E:/Program Files/Derivative/TouchDesigner 099/bin/TouchInit.py", line 175, in tdcustomimport
    r = previousimport(*args, **kw)
  File "C:/Users/matteo/Anaconda3/envs/tensorflow/Lib/site-packages\scipy\linalg\misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "E:/Program Files/Derivative/TouchDesigner 099/bin/TouchInit.py", line 175, in tdcustomimport
    r = previousimport(*args, **kw)
  File "C:/Users/matteo/Anaconda3/envs/tensorflow/Lib/site-packages\scipy\linalg\blas.py", line 155, in <module>
    from scipy.linalg import _fblas
  File "E:/Program Files/Derivative/TouchDesigner 099/bin/TouchInit.py", line 175, in tdcustomimport
    r = previousimport(*args, **kw)
  File "E:/Program Files/Derivative/TouchDesigner 099/bin/TouchInit.py", line 175, in tdcustomimport
    r = previousimport(*args, **kw)
ImportError: numpy.core.multiarray failed to import

Traceback (most recent call last):
  File "/StyleTransfer/UI/chopexec1", line 3, in onOffToOn
td.Error: Module compilation error. See operator for details. <type:textDAT path:/StyleTransfer/local/modules/main> <class 'td.textDAT'>
python >>>

**Comment by exsstas** [comment]
That's numpy. (check step 4-5 in readme - setup section). Easiest way to deal with it: go to you touchdesigner folder  \bin\Lib\site-packages\  and rename _numpy_ to something else. TouchDesigner will start to use numpy from Anaconda. If you'll need in future to use original numpy, you can rename this folder back.

**Comment by matewfeel** [comment]
Thanks i got it to work !
