### ISSUE TITLE
Error run style transfer

### ISSUE THREAD

**Issue by YvesBB** [exsstas/StyleTransfer-in-TD#2]
Hello i have that error when i run style transfer in gpu, it works in the script check gpu:
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\Lib\site-packages\tensorflow\python\client\session.py", line 1322, in _do_call
    return fn(*args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\Lib\site-packages\tensorflow\python\client\session.py", line 1305, in _run_fn
    self._extend_graph()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\Lib\site-packages\tensorflow\python\client\session.py", line 1340, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'L2Loss': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Registered kernels:
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]

thanks a lot Yves

**Comment by exsstas** [comment]
Please, test a new version of StyleTransfer.toe - i hope it will solve the issue

**Comment by YvesBB** [comment]
Thanks a lot
that's solved the issue!
